### ISSUE TITLE
dpemotes Clash

### ISSUE THREAD

**Issue by DowntownRoleplay** [chickenlord01/johnspolicemenu#3]
Hey, I am trying to change my button mapped keybinds for the menu and it isn't working. I have reinstalled the menu and dpemotes multiple times and it doesn't change. I have changed the keybind in the config for both of them and it always comes back to F3. Any ideas?

Nothing is changing from F3 for both dpemotes and the police menu.

**Comment by chickenlord01** [comment]
The keybind settings for my menu and dpemotes are 2 different things. Whatever you set it to in the menu config is what it will be for the police menu. To change the button for the dpemotes you will need to change it in config for that resource

**Comment by DowntownRoleplay** [comment]
I understand and knew that prior to sending this issue in, I am stating that the menu buttons are not changing, I am changing the keybinds and it's not changing the police menu nor the dpemotes (when I change both configs). I stated dpemotes because it's a requirement and it's not changing from the same button as the police menu.

**Comment by chickenlord01** [comment]
Quick explanation on how the keymapping works. Whatever key you have set in the config is the key it sets for the client when they first join. If you change it after that it will not change for the client. You will need to either unbind the current setting on the client by entering this into the game console (F8): unbind keyboard F3. F3 being the key that it is set too. As far as changing it on the client when it is already set, enter the normal GTA V pause menu and go to settings>keybinds>fivem (way bottom). The client can change the keybind in there.

The reason it is coded like this: It will allow players to modify how they want their keybind to be so they are not forced to use whatever is set for them.

Here is a cook book post about keymapping: https://cookbook.fivem.net/2020/01/06/using-the-new-console-key-bindings/

**Comment by chickenlord01** [comment]
I am assuming this is resolved so I will be closing it.
